# STOCK GROUPS

Here we will group and combine the stocks in each stock sector-level to form a single datafram. We will carefully apply weights to the data. 

NOTE: We will use the data in the feature_engineering folder to get this done. We could have done this combination before feature engineering but not to worry we will continue from here

In [2]:
import pandas as pd
RONCHESS=pd.read_csv('stock_data/RONCHESS.csv')

In [3]:
RONCHESS.head(60)

,id,symbol,trade_date,open_price,high_price,low_price,close_price,volume,created_at
0,162740,RONCHESS,2021-12-17,81.0,NaN,NaN,81,0.0,2026-04-08T03:47:01.752329+00:00
1,162851,RONCHESS,2021-12-20,81.0,NaN,NaN,81,0.0,2026-04-08T03:47:06.293287+00:00
2,162962,RONCHESS,2021-12-21,81.0,NaN,NaN,81,0.0,2026-04-08T03:47:08.729464+00:00
3,163073,RONCHESS,2021-12-22,81.0,NaN,NaN,81,0.0,2026-04-08T03:47:11.106283+00:00
4,163184,RONCHESS,2021-12-23,81.0,NaN,NaN,81,0.0,2026-04-08T03:47:13.420215+00:00
5,163295,RONCHESS,2021-12-24,81.0,NaN,NaN,81,0.0,2026-04-08T03:47:15.708642+00:00
6,163406,RONCHESS,2021-12-29,81.0,NaN,NaN,81,0.0,2026-04-08T03:47:22.624079+00:00
7,163517,RONCHESS,2021-12-30,81.0,NaN,NaN,81,0.0,2026-04-08T03:47:25.019388+00:00
8,163628,RONCHESS,2021-12-31,81.0,NaN,NaN,81,0.0,2026-04-08T03:47:27.803632+00:00
9,163739,RONCHESS,2022-01-04,81.0,NaN,NaN,81,0.0,2026-04-08T03:47:33.190226+00:00
10,163851,RONCHESS,2022-01-05,81.0,NaN,NaN,81,0.0,2026-04-08T03:47:35.481449+00:00
11,163963,RONCHESS,2022-01-06,81.0,NaN,NaN,81,0.0,2026-04-08T03:47:38.067383+00:00
12,164075,RONCHESS,2022-01-07,81.0,NaN,NaN,81,0.0,2026-04-08T03:47:40.483305+00:00
13,164187,RONCHESS,2022-01-10,81.0,NaN,NaN,81,0.0,2026-04-08T03:47:45.097739+00:00
14,164299,RONCHESS,2022-01-11,81.0,NaN,NaN,81,0.0,2026-04-08T03:47:47.617941+00:00
15,164411,RONCHESS,2022-01-12,81.0,NaN,NaN,81,0.0,2026-04-08T03:47:50.132225+00:00
16,164523,RONCHESS,2022-01-13,81.0,NaN,NaN,81,0.0,2026-04-08T03:47:52.673244+00:00
17,164635,RONCHESS,2022-01-14,81.0,NaN,NaN,81,0.0,2026-04-08T03:47:55.308832+00:00
18,164747,RONCHESS,2022-01-17,81.0,NaN,NaN,81,0.0,2026-04-08T03:47:59.999655+00:00
19,164859,RONCHESS,2022-01-18,81.0,NaN,NaN,81,0.0,2026-04-08T03:48:02.353596+00:00
20,164971,RONCHESS,2022-01-19,81.0,NaN,NaN,81,0.0,2026-04-08T03:48:04.820784+00:00
21,165083,RONCHESS,2022-01-20,81.0,NaN,NaN,81,0.0,2026-04-08T03:48:07.325935+00:00
22,165195,RONCHESS,2022-01-21,81.0,NaN,NaN,81,0.0,2026-04-08T03:48:09.696329+00:00
23,165307,RONCHESS,2022-01-24,81.0,NaN,NaN,81,0.0,2026-04-08T03:48:14.136661+00:00
24,165419,RONCHESS,2022-01-25,81.0,NaN,NaN,81,0.0,2026-04-08T03:48:16.50614+00:00
25,165531,RONCHESS,2022-01-26,81.0,NaN,NaN,81,0.0,2026-04-08T03:48:19.024911+00:00
26,165643,RONCHESS,2022-01-27,81.0,NaN,NaN,81,0.0,2026-04-08T03:48:21.585909+00:00
27,165755,RONCHESS,2022-01-28,81.0,NaN,NaN,81,0.0,2026-04-08T03:48:23.969021+00:00
28,165867,RONCHESS,2022-01-31,81.0,NaN,NaN,81,0.0,2026-04-08T03:48:28.465348+00:00
29,165979,RONCHESS,2022-02-01,81.0,NaN,NaN,81,0.0,2026-04-08T03:48:30.807911+00:00
30,166091,RONCHESS,2022-02-02,81.0,NaN,NaN,81,0.0,2026-04-08T03:48:33.305516+00:00
31,166203,RONCHESS,2022-02-03,81.0,NaN,NaN,81,0.0,2026-04-08T03:48:35.918914+00:00
32,166315,RONCHESS,2022-02-04,81.0,NaN,NaN,81,0.0,2026-04-08T03:48:38.317721+00:00
33,166427,RONCHESS,2022-02-07,81.0,NaN,NaN,81,0.0,2026-04-08T03:48:42.904693+00:00
34,166539,RONCHESS,2022-02-08,81.0,NaN,NaN,81,0.0,2026-04-08T03:48:45.378139+00:00
35,166651,RONCHESS,2022-02-09,81.0,NaN,NaN,81,0.0,2026-04-08T03:48:48.035665+00:00
36,166763,RONCHESS,2022-02-10,81.0,NaN,NaN,81,0.0,2026-04-08T03:48:50.398564+00:00
37,166875,RONCHESS,2022-02-11,81.0,NaN,NaN,81,0.0,2026-04-08T03:48:52.774016+00:00
38,166987,RONCHESS,2022-02-14,81.0,NaN,NaN,81,0.0,2026-04-08T03:48:57.293433+00:00
39,167099,RONCHESS,2022-02-15,81.0,NaN,NaN,81,0.0,2026-04-08T03:48:59.662493+00:00
40,167211,RONCHESS,2022-02-16,81.0,NaN,NaN,81,0.0,2026-04-08T03:49:02.003783+00:00
41,167323,RONCHESS,2022-02-17,81.0,NaN,NaN,81,0.0,2026-04-08T03:49:04.32656+00:00
42,167435,RONCHESS,2022-02-18,81.0,NaN,NaN,81,0.0,2026-04-08T03:49:06.711382+00:00
43,167547,RONCHESS,2022-02-21,81.0,NaN,NaN,81,0.0,2026-04-08T03:49:10.978464+00:00
44,167659,RONCHESS,2022-02-22,81.0,NaN,NaN,81,0.0,2026-04-08T03:49:13.528869+00:00
45,167771,RONCHESS,2022-02-23,81.0,NaN,NaN,81,0.0,2026-04-08T03:49:15.914345+00:00
46,167883,RONCHESS,2022-02-24,81.0,NaN,NaN,81,0.0,2026-04-08T03:49:18.676795+00:00
47,167995,RONCHESS,2022-02-25,81.0,NaN,NaN,81,0.0,2026-04-08T03:49:21.264729+00:00
48,168107,RONCHESS,2022-02-28,81.0,NaN,NaN,81,0.0,2026-04-08T03:49:25.620712+00:00
49,168219,RONCHESS,2022-03-01,81.0,NaN,NaN,81,0.0,2026-04-08T03:49:28.049171+00:00
50,168331,RONCHESS,2022-03-02,81.0,NaN,NaN,81,0.0,2026-04-08T03:49:30.283109+00:00
51,168443,RONCHESS,2022-03-03,81.0,NaN,NaN,81,0.0,2026-04-08T03:49:32.551227+00:00
52,168555,RONCHESS,2022-03-04,81.0,NaN,NaN,81,0.0,2026-04-08T03:49:34.968546+00:00
53,168667,RONCHESS,2022-03-07,81.0,NaN,NaN,81,0.0,2026-04-08T03:49:39.227432+00:00
54,168779,RONCHESS,2022-03-08,81.0,NaN,NaN,81,0.0,2026-04-08T03:49:41.475537+00:00
55,168891,RONCHESS,2022-03-09,81.0,NaN,NaN,81,0.0,2026-04-08T03:49:43.759827+00:00
56,169003,RONCHESS,2022-03-10,81.0,NaN,NaN,81,0.0,2026-04-08T03:49:46.077826+00:00
57,169115,RONCHESS,2022-03-11,81.0,NaN,NaN,81,0.0,2026-04-08T03:49:48.438529+00:00
58,169227,RONCHESS,2022-03-14,81.0,NaN,NaN,81,0.0,2026-04-08T03:49:53.114563+00:00
59,169339,RONCHESS,2022-03-15,81.0,NaN,NaN,81,0.0,2026-04-08T03:49:55.533531+00:00

In [4]:
RONCHESS.tail(60)

,id,symbol,trade_date,open_price,high_price,low_price,close_price,volume,created_at
1013,280164,RONCHESS,2026-04-21,81.0,NaN,NaN,81,NaN,2026-04-21T15:00:02.189846+00:00
1014,280310,RONCHESS,2026-04-22,81.0,NaN,NaN,81,NaN,2026-04-22T15:00:02.200159+00:00
1015,280456,RONCHESS,2026-04-23,81.0,NaN,NaN,81,NaN,2026-04-23T15:00:02.125151+00:00
1016,280602,RONCHESS,2026-04-24,81.0,NaN,NaN,81,NaN,2026-04-24T15:00:02.20649+00:00
1017,280748,RONCHESS,2026-04-27,81.0,NaN,NaN,81,NaN,2026-04-27T15:00:02.034997+00:00
1018,280894,RONCHESS,2026-04-28,81.0,NaN,NaN,81,NaN,2026-04-28T15:00:01.918241+00:00
1019,281040,RONCHESS,2026-04-29,81.0,NaN,NaN,81,NaN,2026-04-29T15:00:02.672724+00:00
1020,281186,RONCHESS,2026-04-30,81.0,NaN,NaN,81,NaN,2026-04-30T15:00:02.170664+00:00
1021,281478,RONCHESS,2026-05-04,81.0,NaN,NaN,81,NaN,2026-05-04T15:00:02.156928+00:00
1022,281624,RONCHESS,2026-05-05,81.0,NaN,NaN,81,NaN,2026-05-05T15:00:01.930748+00:00
1023,281770,RONCHESS,2026-05-06,81.0,NaN,NaN,81,NaN,2026-05-06T15:00:01.919787+00:00
1024,281916,RONCHESS,2026-05-07,81.0,NaN,NaN,81,NaN,2026-05-07T15:00:01.995523+00:00
1025,282062,RONCHESS,2026-05-08,81.0,NaN,NaN,81,NaN,2026-05-08T15:00:02.118161+00:00
1026,282208,RONCHESS,2026-05-11,81.0,NaN,NaN,81,NaN,2026-05-11T15:00:02.243132+00:00
1027,282354,RONCHESS,2026-05-12,81.0,NaN,NaN,81,NaN,2026-05-12T15:00:02.325735+00:00
1028,282500,RONCHESS,2026-05-13,81.0,NaN,NaN,81,NaN,2026-05-13T15:00:01.887561+00:00
1029,282646,RONCHESS,2026-05-14,81.0,NaN,NaN,81,NaN,2026-05-14T15:00:01.952989+00:00
1030,282792,RONCHESS,2026-05-15,81.0,NaN,NaN,81,NaN,2026-05-15T15:00:01.871578+00:00
1031,282938,RONCHESS,2026-05-18,81.0,NaN,NaN,81,NaN,2026-05-18T15:00:01.868607+00:00
1032,283084,RONCHESS,2026-05-19,81.0,NaN,NaN,81,NaN,2026-05-19T15:00:01.863653+00:00
1033,283230,RONCHESS,2026-05-20,81.0,NaN,NaN,81,NaN,2026-05-20T15:00:01.871845+00:00
1034,283376,RONCHESS,2026-05-21,81.0,NaN,NaN,81,NaN,2026-05-21T15:00:01.939198+00:00
1035,283522,RONCHESS,2026-05-22,81.0,NaN,NaN,81,NaN,2026-05-22T15:00:02.031345+00:00
1036,283668,RONCHESS,2026-05-25,81.0,NaN,NaN,81,NaN,2026-05-25T15:00:01.979384+00:00
1037,283814,RONCHESS,2026-05-26,81.0,NaN,NaN,81,NaN,2026-05-26T15:00:01.996051+00:00
1038,284252,RONCHESS,2026-05-29,81.0,NaN,NaN,81,NaN,2026-05-29T15:00:02.455558+00:00
1039,284398,RONCHESS,2026-06-01,81.0,NaN,NaN,81,NaN,2026-06-01T15:00:02.603507+00:00
1040,284544,RONCHESS,2026-06-02,81.0,NaN,NaN,81,NaN,2026-06-02T15:00:02.980523+00:00
1041,284690,RONCHESS,2026-06-03,81.0,NaN,NaN,81,NaN,2026-06-03T15:00:03.023028+00:00
1042,284836,RONCHESS,2026-06-04,81.0,NaN,NaN,81,NaN,2026-06-04T15:00:03.321931+00:00
1043,284982,RONCHESS,2026-06-05,81.0,NaN,NaN,81,NaN,2026-06-05T15:00:03.073061+00:00
1044,285128,RONCHESS,2026-06-08,81.0,NaN,NaN,81,NaN,2026-06-08T15:00:03.135386+00:00
1045,285274,RONCHESS,2026-06-09,81.0,NaN,NaN,81,NaN,2026-06-09T15:00:03.53749+00:00
1046,285420,RONCHESS,2026-06-10,81.0,NaN,NaN,81,NaN,2026-06-10T15:10:03.084397+00:00
1047,285858,RONCHESS,2026-06-11,81.0,NaN,NaN,81,NaN,2026-06-11T15:10:02.991492+00:00
1048,287610,RONCHESS,2026-06-15,81.0,NaN,NaN,81,NaN,2026-06-15T15:10:02.896252+00:00
1049,288486,RONCHESS,2026-06-16,81.0,NaN,NaN,81,NaN,2026-06-16T15:10:02.87997+00:00
1050,289362,RONCHESS,2026-06-17,81.0,NaN,NaN,81,NaN,2026-06-17T15:10:02.980097+00:00
1051,289800,RONCHESS,2026-06-18,81.0,NaN,NaN,81,NaN,2026-06-18T15:10:02.932064+00:00
1052,290384,RONCHESS,2026-06-19,81.0,NaN,NaN,81,NaN,2026-06-19T15:10:02.959085+00:00
1053,291114,RONCHESS,2026-06-22,81.0,NaN,NaN,81,NaN,2026-06-22T15:10:03.140564+00:00
1054,291698,RONCHESS,2026-06-23,81.0,NaN,NaN,81,NaN,2026-06-23T15:10:03.017319+00:00
1055,292282,RONCHESS,2026-06-24,81.0,NaN,NaN,81,NaN,2026-06-24T15:10:03.053149+00:00
1056,292866,RONCHESS,2026-06-25,81.0,NaN,NaN,81,NaN,2026-06-25T15:10:02.973562+00:00
1057,293304,RONCHESS,2026-06-26,81.0,NaN,NaN,81,NaN,2026-06-26T15:10:03.012808+00:00
1058,293742,RONCHESS,2026-06-29,81.0,NaN,NaN,81,NaN,2026-06-29T15:10:03.028054+00:00
1059,294180,RONCHESS,2026-06-30,81.0,NaN,NaN,81,NaN,2026-06-30T15:10:03.08168+00:00
1060,294618,RONCHESS,2026-07-01,81.0,NaN,NaN,81,NaN,2026-07-01T15:10:03.133226+00:00
1061,295056,RONCHESS,2026-07-02,81.0,NaN,NaN,81,NaN,2026-07-02T15:10:03.065554+00:00
1062,295494,RONCHESS,2026-07-03,81.0,NaN,NaN,81,NaN,2026-07-03T15:10:03.019266+00:00
1063,295932,RONCHESS,2026-07-06,81.0,NaN,NaN,81,NaN,2026-07-06T15:10:03.100823+00:00
1064,296370,RONCHESS,2026-07-07,81.0,NaN,NaN,81,NaN,2026-07-07T15:10:03.687653+00:00
1065,296808,RONCHESS,2026-07-08,81.0,NaN,NaN,81,NaN,2026-07-08T15:10:02.922872+00:00
1066,297247,RONCHESS,2026-07-09,81.0,NaN,NaN,81,NaN,2026-07-09T15:10:03.041812+00:00
1067,297685,RONCHESS,2026-07-10,81.0,NaN,NaN,81,NaN,2026-07-10T15:10:03.284445+00:00
1068,298123,RONCHESS,2026-07-13,81.0,NaN,NaN,81,NaN,2026-07-13T15:10:02.995074+00:00
1069,298561,RONCHESS,2026-07-14,81.0,NaN,NaN,81,NaN,2026-07-14T15:10:03.094441+00:00
1070,298999,RONCHESS,2026-07-15,81.0,NaN,NaN,81,NaN,2026-07-15T15:10:03.078609+00:00
1071,299437,RONCHESS,2026-07-16,81.0,NaN,NaN,81,NaN,2026-07-16T15:10:03.113936+00:00
1072,299875,RONCHESS,2026-07-17,81.0,NaN,NaN,81,NaN,2026-07-17T15:10:03.053983+00:00

In [5]:
RONCHESS['close_price'].unique()

array([81])

RONCHESS STOCK DATA IS HIGHLY NOT USEFUL. We can find the data elsewhere but we are out of time.

In [6]:
STACO=pd.read_csv('stock_data/STACO.csv')

In [8]:
STACO.head(60)

,id,symbol,trade_date,open_price,high_price,low_price,close_price,volume,created_at
0,81318,STACO,2018-09-11,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:07:53.572062+00:00
1,81420,STACO,2018-09-12,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:07:56.190409+00:00
2,81522,STACO,2018-09-13,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:07:58.529226+00:00
3,81624,STACO,2018-09-14,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:08:00.944137+00:00
4,81726,STACO,2018-09-17,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:08:05.572353+00:00
5,81828,STACO,2018-09-18,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:08:07.840784+00:00
6,81930,STACO,2018-09-19,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:08:10.07554+00:00
7,82032,STACO,2018-09-20,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:08:12.389642+00:00
8,82134,STACO,2018-09-21,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:08:14.761127+00:00
9,82236,STACO,2018-09-24,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:08:19.182113+00:00
10,82338,STACO,2018-09-25,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:08:21.370615+00:00
11,82440,STACO,2018-09-26,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:08:24.494451+00:00
12,82542,STACO,2018-09-27,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:08:26.812803+00:00
13,82644,STACO,2018-09-28,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:08:29.283021+00:00
14,82746,STACO,2018-10-02,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:08:34.887787+00:00
15,82848,STACO,2018-10-04,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:08:38.279141+00:00
16,82950,STACO,2018-10-05,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:08:40.455926+00:00
17,83052,STACO,2018-10-08,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:08:45.286665+00:00
18,83154,STACO,2018-10-09,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:08:47.584215+00:00
19,83256,STACO,2018-10-10,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:08:50.198924+00:00
20,83358,STACO,2018-10-11,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:08:52.595743+00:00
21,83460,STACO,2018-10-12,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:08:54.923298+00:00
22,83562,STACO,2018-10-15,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:08:59.688494+00:00
23,83664,STACO,2018-10-16,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:09:01.98694+00:00
24,83766,STACO,2018-10-17,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:09:04.302348+00:00
25,83868,STACO,2018-10-18,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:09:06.644992+00:00
26,83970,STACO,2018-10-19,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:09:09.038287+00:00
27,84072,STACO,2018-10-22,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:09:13.967+00:00
28,84174,STACO,2018-10-23,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:09:16.194722+00:00
29,84276,STACO,2018-10-24,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:09:18.448083+00:00
30,84378,STACO,2018-10-25,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:09:20.631413+00:00
31,84480,STACO,2018-10-26,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:09:23.109094+00:00
32,84582,STACO,2018-10-29,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:09:27.901396+00:00
33,84684,STACO,2018-10-30,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:09:30.377337+00:00
34,84786,STACO,2018-10-31,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:09:32.658485+00:00
35,84888,STACO,2018-11-01,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:09:35.048509+00:00
36,84990,STACO,2018-11-02,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:09:37.41202+00:00
37,85092,STACO,2018-11-05,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:09:41.998643+00:00
38,85194,STACO,2018-11-06,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:09:44.485046+00:00
39,85296,STACO,2018-11-08,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:09:47.843283+00:00
40,85398,STACO,2018-11-09,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:09:50.169754+00:00
41,85500,STACO,2018-11-12,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:09:54.975549+00:00
42,85602,STACO,2018-11-13,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:09:57.558923+00:00
43,85704,STACO,2018-11-14,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:09:59.910116+00:00
44,85806,STACO,2018-11-15,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:10:02.252366+00:00
45,85908,STACO,2018-11-16,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:10:04.527169+00:00
46,86010,STACO,2018-11-19,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:10:09.122468+00:00
47,86112,STACO,2018-11-21,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:10:12.622729+00:00
48,86214,STACO,2018-11-22,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:10:14.989948+00:00
49,86316,STACO,2018-11-23,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:10:17.221139+00:00
50,86418,STACO,2018-11-26,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:10:22.142454+00:00
51,86520,STACO,2018-11-27,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:10:24.421595+00:00
52,86622,STACO,2018-11-28,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:10:26.708398+00:00
53,86724,STACO,2018-11-29,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:10:29.255332+00:00
54,86826,STACO,2018-11-30,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:10:32.706086+00:00
55,86928,STACO,2018-12-03,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:10:37.185914+00:00
56,87030,STACO,2018-12-04,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:10:39.607482+00:00
57,87132,STACO,2018-12-05,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:10:42.037497+00:00
58,87234,STACO,2018-12-06,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:10:44.312069+00:00
59,87336,STACO,2018-12-07,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:10:46.663078+00:00

STACO data is also not useful.

In [2]:
## create a pandas dataframe with date from jan 2017 to july 2026

import datetime
import pandas as pd

# Generate dates from January 1, 2017, to today
date_series = pd.date_range(start="2017-01-01", end=datetime.date.today())

# Create the DataFrame
sector_df = pd.DataFrame({"date": date_series})

sector_df

           date
0    2017-01-01
1    2017-01-02
2    2017-01-03
3    2017-01-04
4    2017-01-05
...         ...
3494 2026-07-27
3495 2026-07-28
3496 2026-07-29
3497 2026-07-30
3498 2026-07-31

[3499 rows x 1 columns]

In [3]:
## create a sector column. We wil still automate this
sector_df['sector']='agriculture'

In [4]:
sector_df.head()

        date       sector
0 2017-01-01  agriculture
1 2017-01-02  agriculture
2 2017-01-03  agriculture
3 2017-01-04  agriculture
4 2017-01-05  agriculture

### Create sector returns

1. Get the daily returns of each data. 
2. Get use market capitalizaton to get the weighted return.
    - `stock_weight= (stock_mrkt_cap/sector_mrkt_cap)`
    - `stock_weight_return= stock_weight * stock_return`
3. Sum the sector_stock_weight_return

In [5]:
all_stocks=pd.read_csv('stock_data/All_Stocks_Info')

In [6]:
all_stocks.head()

,symbol,name,current_price,previous_close,change_percent,official_change_percent,pct_change_7d,volume,market_cap,shares_outstanding,sector,market,trade_date
0,AIRTELAFRI,Airtel Africa Plc,5801.4,5801.4,0.00,NaN,0.00,7865.0,2.180254e+13,3.758152e+09,ICT,Main Board,2026-07-17T00:00:00
1,DANGCEM,Dangote Cement Plc,1047.0,1047.0,0.00,NaN,0.00,388188.0,1.766662e+13,1.687356e+10,INDUSTRIAL GOODS,Premium Board,2026-07-17T00:00:00
2,MTNN,MTN Nigeria Communications Plc,826.5,823.5,0.36,0.36,2.04,1405579.0,1.735283e+13,2.099556e+10,ICT,Premium Board,2026-07-17T00:00:00
3,BUAFOODS,BUA Foods Plc,939.0,939.0,0.00,NaN,0.00,67968.0,1.690200e+13,1.800000e+10,CONSUMER GOODS,Main Board,2026-07-17T00:00:00
4,BUACEMENT,BUA Cement Plc,275.6,275.6,-0.58,-0.58,-18.99,17411684.0,9.333016e+12,3.386435e+10,INDUSTRIAL GOODS,Main Board,2026-07-17T00:00:00

In [7]:
def get_market_cap(ticker: str, all_stocks: pd.DataFrame):
    return all_stocks.loc[
        all_stocks['symbol'] == ticker,
        'market_cap'
    ].iloc[0]

In [8]:
print(all_stocks.columns)
print(all_stocks['symbol'].head())
print(all_stocks[all_stocks['symbol'] == 'BUAFOODS'])

Index(['symbol', 'name', 'current_price', 'previous_close', 'change_percent',
       'official_change_percent', 'pct_change_7d', 'volume', 'market_cap',
       'shares_outstanding', 'sector', 'market', 'trade_date'],
      dtype='str')
0    AIRTELAFRI
1       DANGCEM
2          MTNN
3      BUAFOODS
4     BUACEMENT
Name: symbol, dtype: str
     symbol           name  current_price  previous_close  change_percent  \
3  BUAFOODS  BUA Foods Plc          939.0           939.0             0.0

   official_change_percent  pct_change_7d   volume    market_cap  \
3                      NaN            0.0  67968.0  1.690200e+13

   shares_outstanding          sector      market           trade_date
3        1.800000e+10  CONSUMER GOODS  Main Board  2026-07-17T00:00:00

In [9]:
BUA_MKT_CAP = get_market_cap('BUAFOODS', all_stocks)
print(BUA_MKT_CAP)
print(type(BUA_MKT_CAP))

16902000000000.0
<class 'numpy.float64'>

In [10]:
# Get Sector Market Capitalization. The total for the sector

def get_sector_mkt_cap(all_stocks:pd.DataFrame, stocks_list:list[str]):
    tot_mkt_cap=0
    for stock in stocks_list:
        mkt_cap=get_market_cap(stock,all_stocks)
        tot_mkt_cap+=mkt_cap

    return tot_mkt_cap

# def get_sector_mkt_cap(all_stocks: pd.DataFrame, stocks_list: list[str]):
#     return all_stocks.loc[all_stocks['symbol'].isin(stocks_list), 'market_cap'].sum()

In [11]:
FOLDER_PATH='feature_engineering/stocks_sectors/agriculture'
stock_ticker_list=[]

In [12]:
import os

for csv_data in os.listdir(FOLDER_PATH):
    try:
        # data = pd.read_csv(os.path.join(FOLDER_PATH, csv_data))
        ticker = os.path.splitext(csv_data)[0].split('_')[0] ## Captures the name of the stock
        stock_ticker_list.append(ticker)
    except Exception as e:
            print('Error: ', e)

In [13]:
stock_ticker_list

['ELLAHLAKES', 'FTNCOCOA', 'LIVESTOCK', 'OKOMUOIL']

In [14]:
sector_market_cap=get_sector_mkt_cap(all_stocks,stocks_list=stock_ticker_list)
sector_market_cap

np.float64(1446272938067.7)

In [58]:
# missing = [s for s in stock_ticker_list if s not in all_stocks['symbol'].values]
# print(missing)

In [22]:
## Apply weighted control on the stock returns for each stock in the sector
def weighted_stock_returns(sector_folder:str, sector_market_cap:float, all_stocks:pd.DataFrame) -> dict:
    mutated_stock_data={}
    for csv_data in os.listdir(sector_folder):
        try:
            ticker = os.path.splitext(csv_data)[0].split('_')[0] ## Captures the name of the stock
            data = pd.read_csv(os.path.join(sector_folder, csv_data))
            stock_mkt_cap = get_market_cap(ticker, all_stocks)
            weight=stock_mkt_cap/sector_market_cap
            data['weighted_stock_return']=data['returns_pct']*weight
            ## The trade_date in stock_data should be converted to datetime object
            data['trade_date'] = pd.to_datetime(data['trade_date'], format='%Y-%m-%d', errors='coerce')
            mutated_stock_data[f'{ticker}']=data
        except Exception as e:
            print('Error: ', e)
    return mutated_stock_data

In [23]:
stock_data=weighted_stock_returns(FOLDER_PATH,sector_market_cap,all_stocks)

In [24]:
## Lets confirm this worked
stock_data['ELLAHLAKES']

,id,symbol,trade_date,open_price,close_price,volume,created_at,returns_pct,lag_return1,lag_return5,...,stock_MA_20,stock_MA_50,returns_volatility_20,returns_volatility_50,stock_RSI,MACD,MACD_hist,MACD_signal,stock_volume_MA_20,weighted_stock_return
0,112315,ELLAHLAKES,2019-12-18,4.25,4.25,5000000,2026-04-08T03:23:10.699016+00:00,-0.234742,0.000000,0.000000,...,4.2595,4.2598,0.052490,0.033198,0.000000,-0.000798,-0.000638,-0.000160,250025.00,-0.005636
1,112417,ELLAHLAKES,2019-12-19,4.25,4.25,1735,2026-04-08T03:23:13.06361+00:00,0.000000,-0.234742,0.000000,...,4.2590,4.2596,0.052490,0.033198,0.000000,-0.001414,-0.001003,-0.000410,250111.75,0.000000
2,112519,ELLAHLAKES,2019-12-20,4.25,4.25,0,2026-04-08T03:23:15.515212+00:00,0.000000,0.000000,0.000000,...,4.2585,4.2594,0.052490,0.033198,0.000000,-0.001880,-0.001176,-0.000704,250111.75,0.000000
3,112621,ELLAHLAKES,2019-12-23,4.25,4.25,0,2026-04-08T03:23:19.645113+00:00,0.000000,0.000000,0.000000,...,4.2580,4.2592,0.052490,0.033198,0.000000,-0.002224,-0.001216,-0.001008,250111.75,0.000000
4,112723,ELLAHLAKES,2019-12-24,4.25,4.25,0,2026-04-08T03:23:22.081747+00:00,0.000000,0.000000,0.000000,...,4.2575,4.2590,0.052490,0.033198,0.000000,-0.002468,-0.001168,-0.001300,250111.75,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1547,298053,ELLAHLAKES,2026-07-13,8.75,8.75,7004984,2026-07-13T15:10:02.995074+00:00,-2.777778,-0.552486,-2.958580,...,8.6675,9.6440,3.780850,4.307672,45.738418,-0.255612,0.109485,-0.365097,5387875.85,-0.066692
1548,298491,ELLAHLAKES,2026-07-14,8.55,8.55,9521217,2026-07-14T15:10:03.094441+00:00,-2.285714,-2.777778,2.439024,...,8.6450,9.6150,3.358378,4.164315,43.060188,-0.252266,0.090265,-0.342531,5521457.65,-0.054878
1549,298929,ELLAHLAKES,2026-07-15,8.95,8.95,2351435,2026-07-15T15:10:03.078609+00:00,4.678363,-2.285714,6.547619,...,8.6600,9.5950,3.409425,4.221423,49.437137,-0.214862,0.102136,-0.316997,5336033.15,0.112323
1550,299367,ELLAHLAKES,2026-07-16,8.95,8.95,2042964,2026-07-16T15:10:03.113936+00:00,0.000000,4.678363,1.117318,...,8.6575,9.5560,3.288707,3.984242,49.437137,-0.183107,0.107112,-0.290219,5247735.70,0.000000
1551,299805,ELLAHLAKES,2026-07-17,9.00,9.00,4107698,2026-07-17T15:10:03.053983+00:00,0.558659,0.000000,-0.552486,...,8.6700,9.5100,3.223097,3.944829,50.244955,-0.152153,0.110453,-0.262606,5158069.40,0.013413

In [76]:
stock_data['ELLAHLAKES'].head()

,id,symbol,trade_date,open_price,close_price,volume,created_at,returns_pct,lag_return1,lag_return5,...,stock_MA_20,stock_MA_50,returns_volatility_20,returns_volatility_50,stock_RSI,MACD,MACD_hist,MACD_signal,stock_volume_MA_20,weighted_stock_return
0,112315,ELLAHLAKES,2019-12-18,4.25,4.25,5000000,2026-04-08T03:23:10.699016+00:00,-0.234742,0.000000,0.0,...,4.2595,4.2598,0.05249,0.033198,0.0,-0.000798,-0.000638,-0.000160,250025.00,-0.005636
1,112417,ELLAHLAKES,2019-12-19,4.25,4.25,1735,2026-04-08T03:23:13.06361+00:00,0.000000,-0.234742,0.0,...,4.2590,4.2596,0.05249,0.033198,0.0,-0.001414,-0.001003,-0.000410,250111.75,0.000000
2,112519,ELLAHLAKES,2019-12-20,4.25,4.25,0,2026-04-08T03:23:15.515212+00:00,0.000000,0.000000,0.0,...,4.2585,4.2594,0.05249,0.033198,0.0,-0.001880,-0.001176,-0.000704,250111.75,0.000000
3,112621,ELLAHLAKES,2019-12-23,4.25,4.25,0,2026-04-08T03:23:19.645113+00:00,0.000000,0.000000,0.0,...,4.2580,4.2592,0.05249,0.033198,0.0,-0.002224,-0.001216,-0.001008,250111.75,0.000000
4,112723,ELLAHLAKES,2019-12-24,4.25,4.25,0,2026-04-08T03:23:22.081747+00:00,0.000000,0.000000,0.0,...,4.2575,4.2590,0.05249,0.033198,0.0,-0.002468,-0.001168,-0.001300,250111.75,0.000000

In [77]:
## PERFECT! Now we have it in a dictioanary
## We now have to find the corresponding sums and include it in the sector_df

In [25]:
import datetime as dt
print(sector_df['date'].dtypes)
print(stock_data['ELLAHLAKES']['trade_date'].dtypes)

datetime64[us]
datetime64[us]

In [26]:
def weighted_sector_stock_return(weighted_stocks_returns_dict:dict, sector_df:pd.DataFrame) -> pd.DataFrame:
    # Concatenate all dataframes, keeping only date + weighted_returns
    combined = pd.concat(
        [df[['trade_date', 'weighted_stock_return']] for df in weighted_stocks_returns_dict.values()],
        ignore_index=True
    )

    # Sum weighted_returns per date across all stocks
    daily_totals = combined.groupby('trade_date')['weighted_stock_return'].sum()

    # Map onto sector_df based on matching dates
    sector_df['weighted_sector_returns'] = sector_df['date'].map(daily_totals)

    return sector_df

In [27]:
weighted_sector_df=weighted_sector_stock_return(stock_data,sector_df)

In [28]:
w_df=weighted_sector_df.dropna()

In [29]:
w_df.head(60)

          date       sector  weighted_sector_returns
72  2017-03-14  agriculture                 0.000000
73  2017-03-15  agriculture                 0.000000
74  2017-03-16  agriculture                 0.028035
75  2017-03-17  agriculture                -0.027604
78  2017-03-20  agriculture                -0.028035
79  2017-03-21  agriculture                 0.085441
80  2017-03-22  agriculture                 0.000000
81  2017-03-23  agriculture                 0.081558
82  2017-03-24  agriculture                 0.052008
85  2017-03-27  agriculture                -0.075814
86  2017-03-28  agriculture                -0.079159
87  2017-03-29  agriculture                -0.082812
88  2017-03-30  agriculture                 0.000000
89  2017-03-31  agriculture                 3.810106
92  2017-04-03  agriculture                 0.049117
93  2017-04-04  agriculture                 4.854803
94  2017-04-05  agriculture                 0.081558
95  2017-04-06  agriculture                 0.052008
96  2017-04-07  agriculture                -0.050543
99  2017-04-10  agriculture                -0.052008
100 2017-04-11  agriculture                -0.080340
101 2017-04-12  agriculture                 0.000000
102 2017-04-13  agriculture                 0.000000
107 2017-04-18  agriculture                -0.084106
108 2017-04-19  agriculture                -4.772569
109 2017-04-20  agriculture                -4.606940
110 2017-04-21  agriculture                 0.366612
113 2017-04-24  agriculture                -1.772076
114 2017-04-25  agriculture                -0.082812
115 2017-04-26  agriculture                 2.809801
116 2017-04-27  agriculture                -1.677401
117 2017-04-28  agriculture                 0.158318
121 2017-05-02  agriculture                 0.072741
122 2017-05-03  agriculture                 0.069906
123 2017-05-04  agriculture                 0.067285
124 2017-05-05  agriculture                 0.064853
127 2017-05-08  agriculture                 1.553444
128 2017-05-09  agriculture                 1.428923
129 2017-05-10  agriculture                 2.912628
130 2017-05-11  agriculture                 1.870524
131 2017-05-12  agriculture                -1.911020
134 2017-05-15  agriculture                -0.080641
135 2017-05-16  agriculture                 0.000000
136 2017-05-17  agriculture                -0.084436
137 2017-05-18  agriculture                -0.044303
138 2017-05-19  agriculture                 0.068137
141 2017-05-22  agriculture                 1.683472
142 2017-05-23  agriculture                 0.000000
143 2017-05-24  agriculture                 0.000000
144 2017-05-25  agriculture                 0.153169
145 2017-05-26  agriculture                 3.799950
149 2017-05-30  agriculture                -0.823592
150 2017-05-31  agriculture                 0.020160
151 2017-06-01  agriculture                 0.019936
152 2017-06-02  agriculture                 4.453629
155 2017-06-05  agriculture                 4.676311
156 2017-06-06  agriculture                -0.078869
157 2017-06-07  agriculture                 0.061871
158 2017-06-08  agriculture                 4.684101
159 2017-06-09  agriculture                 0.000000

In [30]:
w_df.shape

(2212, 3)

## Create Sector Index

Build a sector index starting at 100 from the aggregated returns.

Day 1
sector return = 1%

Sector Index = 100 × (1 + 0.01)
             = 101


We will use 100 for all sectors so they can be measured equally. This will the place of hard prices.

In [31]:
def create_sector_index(sector_df: pd.DataFrame) -> pd.DataFrame:
    start_base = 100
    sector_returns = sector_df['weighted_sector_returns'].tolist()

    index_values = []
    for returns in sector_returns:
        start_base = start_base * (1 + (returns / 100))
        index_values.append(start_base)

    sector_df['sector_index'] = index_values
    return sector_df

In [32]:
sector_index_df=create_sector_index(sector_df=w_df)

In [33]:
sector_index_df.head(60)

          date       sector  weighted_sector_returns  sector_index
72  2017-03-14  agriculture                 0.000000    100.000000
73  2017-03-15  agriculture                 0.000000    100.000000
74  2017-03-16  agriculture                 0.028035    100.028035
75  2017-03-17  agriculture                -0.027604    100.000424
78  2017-03-20  agriculture                -0.028035     99.972388
79  2017-03-21  agriculture                 0.085441    100.057806
80  2017-03-22  agriculture                 0.000000    100.057806
81  2017-03-23  agriculture                 0.081558    100.139410
82  2017-03-24  agriculture                 0.052008    100.191491
85  2017-03-27  agriculture                -0.075814    100.115531
86  2017-03-28  agriculture                -0.079159    100.036281
87  2017-03-29  agriculture                -0.082812     99.953439
88  2017-03-30  agriculture                 0.000000     99.953439
89  2017-03-31  agriculture                 3.810106    103.761771
92  2017-04-03  agriculture                 0.049117    103.812735
93  2017-04-04  agriculture                 4.854803    108.852639
94  2017-04-05  agriculture                 0.081558    108.941416
95  2017-04-06  agriculture                 0.052008    108.998074
96  2017-04-07  agriculture                -0.050543    108.942984
99  2017-04-10  agriculture                -0.052008    108.886325
100 2017-04-11  agriculture                -0.080340    108.798845
101 2017-04-12  agriculture                 0.000000    108.798845
102 2017-04-13  agriculture                 0.000000    108.798845
107 2017-04-18  agriculture                -0.084106    108.707339
108 2017-04-19  agriculture                -4.772569    103.519206
109 2017-04-20  agriculture                -4.606940     98.750139
110 2017-04-21  agriculture                 0.366612     99.112169
113 2017-04-24  agriculture                -1.772076     97.355826
114 2017-04-25  agriculture                -0.082812     97.275204
115 2017-04-26  agriculture                 2.809801    100.008443
116 2017-04-27  agriculture                -1.677401     98.330900
117 2017-04-28  agriculture                 0.158318     98.486575
121 2017-05-02  agriculture                 0.072741     98.558215
122 2017-05-03  agriculture                 0.069906     98.627114
123 2017-05-04  agriculture                 0.067285     98.693475
124 2017-05-05  agriculture                 0.064853     98.757481
127 2017-05-08  agriculture                 1.553444    100.291623
128 2017-05-09  agriculture                 1.428923    101.724714
129 2017-05-10  agriculture                 2.912628    104.687576
130 2017-05-11  agriculture                 1.870524    106.645783
131 2017-05-12  agriculture                -1.911020    104.607761
134 2017-05-15  agriculture                -0.080641    104.523404
135 2017-05-16  agriculture                 0.000000    104.523404
136 2017-05-17  agriculture                -0.084436    104.435148
137 2017-05-18  agriculture                -0.044303    104.388880
138 2017-05-19  agriculture                 0.068137    104.460008
141 2017-05-22  agriculture                 1.683472    106.218563
142 2017-05-23  agriculture                 0.000000    106.218563
143 2017-05-24  agriculture                 0.000000    106.218563
144 2017-05-25  agriculture                 0.153169    106.381257
145 2017-05-26  agriculture                 3.799950    110.423692
149 2017-05-30  agriculture                -0.823592    109.514251
150 2017-05-31  agriculture                 0.020160    109.536329
151 2017-06-01  agriculture                 0.019936    109.558167
152 2017-06-02  agriculture                 4.453629    114.437481
155 2017-06-05  agriculture                 4.676311    119.788934
156 2017-06-06  agriculture                -0.078869    119.694458
157 2017-06-07  agriculture                 0.061871    119.768514
158 2017-06-08  agriculture                 4.684101    125.378592
159 2017-06-09  agriculture                 0.000000    125.378592