# STOCK GROUPS

Here we will group and combine the stocks in each stock sector-level to form a single datafram. We will carefully apply weights to the data. 

NOTE: We will use the data in the feature_engineering folder to get this done. We could have done this combination before feature engineering but not to worry we will continue from here

In [2]:
import pandas as pd
RONCHESS=pd.read_csv('stock_data/RONCHESS.csv')

In [3]:
RONCHESS.head(60)

,id,symbol,trade_date,open_price,high_price,low_price,close_price,volume,created_at
0,162740,RONCHESS,2021-12-17,81.0,NaN,NaN,81,0.0,2026-04-08T03:47:01.752329+00:00
1,162851,RONCHESS,2021-12-20,81.0,NaN,NaN,81,0.0,2026-04-08T03:47:06.293287+00:00
2,162962,RONCHESS,2021-12-21,81.0,NaN,NaN,81,0.0,2026-04-08T03:47:08.729464+00:00
3,163073,RONCHESS,2021-12-22,81.0,NaN,NaN,81,0.0,2026-04-08T03:47:11.106283+00:00
4,163184,RONCHESS,2021-12-23,81.0,NaN,NaN,81,0.0,2026-04-08T03:47:13.420215+00:00
5,163295,RONCHESS,2021-12-24,81.0,NaN,NaN,81,0.0,2026-04-08T03:47:15.708642+00:00
6,163406,RONCHESS,2021-12-29,81.0,NaN,NaN,81,0.0,2026-04-08T03:47:22.624079+00:00
7,163517,RONCHESS,2021-12-30,81.0,NaN,NaN,81,0.0,2026-04-08T03:47:25.019388+00:00
8,163628,RONCHESS,2021-12-31,81.0,NaN,NaN,81,0.0,2026-04-08T03:47:27.803632+00:00
9,163739,RONCHESS,2022-01-04,81.0,NaN,NaN,81,0.0,2026-04-08T03:47:33.190226+00:00
10,163851,RONCHESS,2022-01-05,81.0,NaN,NaN,81,0.0,2026-04-08T03:47:35.481449+00:00
11,163963,RONCHESS,2022-01-06,81.0,NaN,NaN,81,0.0,2026-04-08T03:47:38.067383+00:00
12,164075,RONCHESS,2022-01-07,81.0,NaN,NaN,81,0.0,2026-04-08T03:47:40.483305+00:00
13,164187,RONCHESS,2022-01-10,81.0,NaN,NaN,81,0.0,2026-04-08T03:47:45.097739+00:00
14,164299,RONCHESS,2022-01-11,81.0,NaN,NaN,81,0.0,2026-04-08T03:47:47.617941+00:00
15,164411,RONCHESS,2022-01-12,81.0,NaN,NaN,81,0.0,2026-04-08T03:47:50.132225+00:00
16,164523,RONCHESS,2022-01-13,81.0,NaN,NaN,81,0.0,2026-04-08T03:47:52.673244+00:00
17,164635,RONCHESS,2022-01-14,81.0,NaN,NaN,81,0.0,2026-04-08T03:47:55.308832+00:00
18,164747,RONCHESS,2022-01-17,81.0,NaN,NaN,81,0.0,2026-04-08T03:47:59.999655+00:00
19,164859,RONCHESS,2022-01-18,81.0,NaN,NaN,81,0.0,2026-04-08T03:48:02.353596+00:00
20,164971,RONCHESS,2022-01-19,81.0,NaN,NaN,81,0.0,2026-04-08T03:48:04.820784+00:00
21,165083,RONCHESS,2022-01-20,81.0,NaN,NaN,81,0.0,2026-04-08T03:48:07.325935+00:00
22,165195,RONCHESS,2022-01-21,81.0,NaN,NaN,81,0.0,2026-04-08T03:48:09.696329+00:00
23,165307,RONCHESS,2022-01-24,81.0,NaN,NaN,81,0.0,2026-04-08T03:48:14.136661+00:00
24,165419,RONCHESS,2022-01-25,81.0,NaN,NaN,81,0.0,2026-04-08T03:48:16.50614+00:00
25,165531,RONCHESS,2022-01-26,81.0,NaN,NaN,81,0.0,2026-04-08T03:48:19.024911+00:00
26,165643,RONCHESS,2022-01-27,81.0,NaN,NaN,81,0.0,2026-04-08T03:48:21.585909+00:00
27,165755,RONCHESS,2022-01-28,81.0,NaN,NaN,81,0.0,2026-04-08T03:48:23.969021+00:00
28,165867,RONCHESS,2022-01-31,81.0,NaN,NaN,81,0.0,2026-04-08T03:48:28.465348+00:00
29,165979,RONCHESS,2022-02-01,81.0,NaN,NaN,81,0.0,2026-04-08T03:48:30.807911+00:00
30,166091,RONCHESS,2022-02-02,81.0,NaN,NaN,81,0.0,2026-04-08T03:48:33.305516+00:00
31,166203,RONCHESS,2022-02-03,81.0,NaN,NaN,81,0.0,2026-04-08T03:48:35.918914+00:00
32,166315,RONCHESS,2022-02-04,81.0,NaN,NaN,81,0.0,2026-04-08T03:48:38.317721+00:00
33,166427,RONCHESS,2022-02-07,81.0,NaN,NaN,81,0.0,2026-04-08T03:48:42.904693+00:00
34,166539,RONCHESS,2022-02-08,81.0,NaN,NaN,81,0.0,2026-04-08T03:48:45.378139+00:00
35,166651,RONCHESS,2022-02-09,81.0,NaN,NaN,81,0.0,2026-04-08T03:48:48.035665+00:00
36,166763,RONCHESS,2022-02-10,81.0,NaN,NaN,81,0.0,2026-04-08T03:48:50.398564+00:00
37,166875,RONCHESS,2022-02-11,81.0,NaN,NaN,81,0.0,2026-04-08T03:48:52.774016+00:00
38,166987,RONCHESS,2022-02-14,81.0,NaN,NaN,81,0.0,2026-04-08T03:48:57.293433+00:00
39,167099,RONCHESS,2022-02-15,81.0,NaN,NaN,81,0.0,2026-04-08T03:48:59.662493+00:00
40,167211,RONCHESS,2022-02-16,81.0,NaN,NaN,81,0.0,2026-04-08T03:49:02.003783+00:00
41,167323,RONCHESS,2022-02-17,81.0,NaN,NaN,81,0.0,2026-04-08T03:49:04.32656+00:00
42,167435,RONCHESS,2022-02-18,81.0,NaN,NaN,81,0.0,2026-04-08T03:49:06.711382+00:00
43,167547,RONCHESS,2022-02-21,81.0,NaN,NaN,81,0.0,2026-04-08T03:49:10.978464+00:00
44,167659,RONCHESS,2022-02-22,81.0,NaN,NaN,81,0.0,2026-04-08T03:49:13.528869+00:00
45,167771,RONCHESS,2022-02-23,81.0,NaN,NaN,81,0.0,2026-04-08T03:49:15.914345+00:00
46,167883,RONCHESS,2022-02-24,81.0,NaN,NaN,81,0.0,2026-04-08T03:49:18.676795+00:00
47,167995,RONCHESS,2022-02-25,81.0,NaN,NaN,81,0.0,2026-04-08T03:49:21.264729+00:00
48,168107,RONCHESS,2022-02-28,81.0,NaN,NaN,81,0.0,2026-04-08T03:49:25.620712+00:00
49,168219,RONCHESS,2022-03-01,81.0,NaN,NaN,81,0.0,2026-04-08T03:49:28.049171+00:00
50,168331,RONCHESS,2022-03-02,81.0,NaN,NaN,81,0.0,2026-04-08T03:49:30.283109+00:00
51,168443,RONCHESS,2022-03-03,81.0,NaN,NaN,81,0.0,2026-04-08T03:49:32.551227+00:00
52,168555,RONCHESS,2022-03-04,81.0,NaN,NaN,81,0.0,2026-04-08T03:49:34.968546+00:00
53,168667,RONCHESS,2022-03-07,81.0,NaN,NaN,81,0.0,2026-04-08T03:49:39.227432+00:00
54,168779,RONCHESS,2022-03-08,81.0,NaN,NaN,81,0.0,2026-04-08T03:49:41.475537+00:00
55,168891,RONCHESS,2022-03-09,81.0,NaN,NaN,81,0.0,2026-04-08T03:49:43.759827+00:00
56,169003,RONCHESS,2022-03-10,81.0,NaN,NaN,81,0.0,2026-04-08T03:49:46.077826+00:00
57,169115,RONCHESS,2022-03-11,81.0,NaN,NaN,81,0.0,2026-04-08T03:49:48.438529+00:00
58,169227,RONCHESS,2022-03-14,81.0,NaN,NaN,81,0.0,2026-04-08T03:49:53.114563+00:00
59,169339,RONCHESS,2022-03-15,81.0,NaN,NaN,81,0.0,2026-04-08T03:49:55.533531+00:00

In [4]:
RONCHESS.tail(60)

,id,symbol,trade_date,open_price,high_price,low_price,close_price,volume,created_at
1013,280164,RONCHESS,2026-04-21,81.0,NaN,NaN,81,NaN,2026-04-21T15:00:02.189846+00:00
1014,280310,RONCHESS,2026-04-22,81.0,NaN,NaN,81,NaN,2026-04-22T15:00:02.200159+00:00
1015,280456,RONCHESS,2026-04-23,81.0,NaN,NaN,81,NaN,2026-04-23T15:00:02.125151+00:00
1016,280602,RONCHESS,2026-04-24,81.0,NaN,NaN,81,NaN,2026-04-24T15:00:02.20649+00:00
1017,280748,RONCHESS,2026-04-27,81.0,NaN,NaN,81,NaN,2026-04-27T15:00:02.034997+00:00
1018,280894,RONCHESS,2026-04-28,81.0,NaN,NaN,81,NaN,2026-04-28T15:00:01.918241+00:00
1019,281040,RONCHESS,2026-04-29,81.0,NaN,NaN,81,NaN,2026-04-29T15:00:02.672724+00:00
1020,281186,RONCHESS,2026-04-30,81.0,NaN,NaN,81,NaN,2026-04-30T15:00:02.170664+00:00
1021,281478,RONCHESS,2026-05-04,81.0,NaN,NaN,81,NaN,2026-05-04T15:00:02.156928+00:00
1022,281624,RONCHESS,2026-05-05,81.0,NaN,NaN,81,NaN,2026-05-05T15:00:01.930748+00:00
1023,281770,RONCHESS,2026-05-06,81.0,NaN,NaN,81,NaN,2026-05-06T15:00:01.919787+00:00
1024,281916,RONCHESS,2026-05-07,81.0,NaN,NaN,81,NaN,2026-05-07T15:00:01.995523+00:00
1025,282062,RONCHESS,2026-05-08,81.0,NaN,NaN,81,NaN,2026-05-08T15:00:02.118161+00:00
1026,282208,RONCHESS,2026-05-11,81.0,NaN,NaN,81,NaN,2026-05-11T15:00:02.243132+00:00
1027,282354,RONCHESS,2026-05-12,81.0,NaN,NaN,81,NaN,2026-05-12T15:00:02.325735+00:00
1028,282500,RONCHESS,2026-05-13,81.0,NaN,NaN,81,NaN,2026-05-13T15:00:01.887561+00:00
1029,282646,RONCHESS,2026-05-14,81.0,NaN,NaN,81,NaN,2026-05-14T15:00:01.952989+00:00
1030,282792,RONCHESS,2026-05-15,81.0,NaN,NaN,81,NaN,2026-05-15T15:00:01.871578+00:00
1031,282938,RONCHESS,2026-05-18,81.0,NaN,NaN,81,NaN,2026-05-18T15:00:01.868607+00:00
1032,283084,RONCHESS,2026-05-19,81.0,NaN,NaN,81,NaN,2026-05-19T15:00:01.863653+00:00
1033,283230,RONCHESS,2026-05-20,81.0,NaN,NaN,81,NaN,2026-05-20T15:00:01.871845+00:00
1034,283376,RONCHESS,2026-05-21,81.0,NaN,NaN,81,NaN,2026-05-21T15:00:01.939198+00:00
1035,283522,RONCHESS,2026-05-22,81.0,NaN,NaN,81,NaN,2026-05-22T15:00:02.031345+00:00
1036,283668,RONCHESS,2026-05-25,81.0,NaN,NaN,81,NaN,2026-05-25T15:00:01.979384+00:00
1037,283814,RONCHESS,2026-05-26,81.0,NaN,NaN,81,NaN,2026-05-26T15:00:01.996051+00:00
1038,284252,RONCHESS,2026-05-29,81.0,NaN,NaN,81,NaN,2026-05-29T15:00:02.455558+00:00
1039,284398,RONCHESS,2026-06-01,81.0,NaN,NaN,81,NaN,2026-06-01T15:00:02.603507+00:00
1040,284544,RONCHESS,2026-06-02,81.0,NaN,NaN,81,NaN,2026-06-02T15:00:02.980523+00:00
1041,284690,RONCHESS,2026-06-03,81.0,NaN,NaN,81,NaN,2026-06-03T15:00:03.023028+00:00
1042,284836,RONCHESS,2026-06-04,81.0,NaN,NaN,81,NaN,2026-06-04T15:00:03.321931+00:00
1043,284982,RONCHESS,2026-06-05,81.0,NaN,NaN,81,NaN,2026-06-05T15:00:03.073061+00:00
1044,285128,RONCHESS,2026-06-08,81.0,NaN,NaN,81,NaN,2026-06-08T15:00:03.135386+00:00
1045,285274,RONCHESS,2026-06-09,81.0,NaN,NaN,81,NaN,2026-06-09T15:00:03.53749+00:00
1046,285420,RONCHESS,2026-06-10,81.0,NaN,NaN,81,NaN,2026-06-10T15:10:03.084397+00:00
1047,285858,RONCHESS,2026-06-11,81.0,NaN,NaN,81,NaN,2026-06-11T15:10:02.991492+00:00
1048,287610,RONCHESS,2026-06-15,81.0,NaN,NaN,81,NaN,2026-06-15T15:10:02.896252+00:00
1049,288486,RONCHESS,2026-06-16,81.0,NaN,NaN,81,NaN,2026-06-16T15:10:02.87997+00:00
1050,289362,RONCHESS,2026-06-17,81.0,NaN,NaN,81,NaN,2026-06-17T15:10:02.980097+00:00
1051,289800,RONCHESS,2026-06-18,81.0,NaN,NaN,81,NaN,2026-06-18T15:10:02.932064+00:00
1052,290384,RONCHESS,2026-06-19,81.0,NaN,NaN,81,NaN,2026-06-19T15:10:02.959085+00:00
1053,291114,RONCHESS,2026-06-22,81.0,NaN,NaN,81,NaN,2026-06-22T15:10:03.140564+00:00
1054,291698,RONCHESS,2026-06-23,81.0,NaN,NaN,81,NaN,2026-06-23T15:10:03.017319+00:00
1055,292282,RONCHESS,2026-06-24,81.0,NaN,NaN,81,NaN,2026-06-24T15:10:03.053149+00:00
1056,292866,RONCHESS,2026-06-25,81.0,NaN,NaN,81,NaN,2026-06-25T15:10:02.973562+00:00
1057,293304,RONCHESS,2026-06-26,81.0,NaN,NaN,81,NaN,2026-06-26T15:10:03.012808+00:00
1058,293742,RONCHESS,2026-06-29,81.0,NaN,NaN,81,NaN,2026-06-29T15:10:03.028054+00:00
1059,294180,RONCHESS,2026-06-30,81.0,NaN,NaN,81,NaN,2026-06-30T15:10:03.08168+00:00
1060,294618,RONCHESS,2026-07-01,81.0,NaN,NaN,81,NaN,2026-07-01T15:10:03.133226+00:00
1061,295056,RONCHESS,2026-07-02,81.0,NaN,NaN,81,NaN,2026-07-02T15:10:03.065554+00:00
1062,295494,RONCHESS,2026-07-03,81.0,NaN,NaN,81,NaN,2026-07-03T15:10:03.019266+00:00
1063,295932,RONCHESS,2026-07-06,81.0,NaN,NaN,81,NaN,2026-07-06T15:10:03.100823+00:00
1064,296370,RONCHESS,2026-07-07,81.0,NaN,NaN,81,NaN,2026-07-07T15:10:03.687653+00:00
1065,296808,RONCHESS,2026-07-08,81.0,NaN,NaN,81,NaN,2026-07-08T15:10:02.922872+00:00
1066,297247,RONCHESS,2026-07-09,81.0,NaN,NaN,81,NaN,2026-07-09T15:10:03.041812+00:00
1067,297685,RONCHESS,2026-07-10,81.0,NaN,NaN,81,NaN,2026-07-10T15:10:03.284445+00:00
1068,298123,RONCHESS,2026-07-13,81.0,NaN,NaN,81,NaN,2026-07-13T15:10:02.995074+00:00
1069,298561,RONCHESS,2026-07-14,81.0,NaN,NaN,81,NaN,2026-07-14T15:10:03.094441+00:00
1070,298999,RONCHESS,2026-07-15,81.0,NaN,NaN,81,NaN,2026-07-15T15:10:03.078609+00:00
1071,299437,RONCHESS,2026-07-16,81.0,NaN,NaN,81,NaN,2026-07-16T15:10:03.113936+00:00
1072,299875,RONCHESS,2026-07-17,81.0,NaN,NaN,81,NaN,2026-07-17T15:10:03.053983+00:00

In [5]:
RONCHESS['close_price'].unique()

array([81])

RONCHESS STOCK DATA IS HIGHLY NOT USEFUL. We can find the data elsewhere but we are out of time.

In [6]:
STACO=pd.read_csv('stock_data/STACO.csv')

In [8]:
STACO.head(60)

,id,symbol,trade_date,open_price,high_price,low_price,close_price,volume,created_at
0,81318,STACO,2018-09-11,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:07:53.572062+00:00
1,81420,STACO,2018-09-12,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:07:56.190409+00:00
2,81522,STACO,2018-09-13,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:07:58.529226+00:00
3,81624,STACO,2018-09-14,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:08:00.944137+00:00
4,81726,STACO,2018-09-17,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:08:05.572353+00:00
5,81828,STACO,2018-09-18,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:08:07.840784+00:00
6,81930,STACO,2018-09-19,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:08:10.07554+00:00
7,82032,STACO,2018-09-20,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:08:12.389642+00:00
8,82134,STACO,2018-09-21,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:08:14.761127+00:00
9,82236,STACO,2018-09-24,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:08:19.182113+00:00
10,82338,STACO,2018-09-25,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:08:21.370615+00:00
11,82440,STACO,2018-09-26,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:08:24.494451+00:00
12,82542,STACO,2018-09-27,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:08:26.812803+00:00
13,82644,STACO,2018-09-28,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:08:29.283021+00:00
14,82746,STACO,2018-10-02,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:08:34.887787+00:00
15,82848,STACO,2018-10-04,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:08:38.279141+00:00
16,82950,STACO,2018-10-05,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:08:40.455926+00:00
17,83052,STACO,2018-10-08,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:08:45.286665+00:00
18,83154,STACO,2018-10-09,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:08:47.584215+00:00
19,83256,STACO,2018-10-10,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:08:50.198924+00:00
20,83358,STACO,2018-10-11,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:08:52.595743+00:00
21,83460,STACO,2018-10-12,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:08:54.923298+00:00
22,83562,STACO,2018-10-15,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:08:59.688494+00:00
23,83664,STACO,2018-10-16,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:09:01.98694+00:00
24,83766,STACO,2018-10-17,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:09:04.302348+00:00
25,83868,STACO,2018-10-18,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:09:06.644992+00:00
26,83970,STACO,2018-10-19,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:09:09.038287+00:00
27,84072,STACO,2018-10-22,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:09:13.967+00:00
28,84174,STACO,2018-10-23,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:09:16.194722+00:00
29,84276,STACO,2018-10-24,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:09:18.448083+00:00
30,84378,STACO,2018-10-25,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:09:20.631413+00:00
31,84480,STACO,2018-10-26,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:09:23.109094+00:00
32,84582,STACO,2018-10-29,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:09:27.901396+00:00
33,84684,STACO,2018-10-30,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:09:30.377337+00:00
34,84786,STACO,2018-10-31,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:09:32.658485+00:00
35,84888,STACO,2018-11-01,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:09:35.048509+00:00
36,84990,STACO,2018-11-02,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:09:37.41202+00:00
37,85092,STACO,2018-11-05,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:09:41.998643+00:00
38,85194,STACO,2018-11-06,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:09:44.485046+00:00
39,85296,STACO,2018-11-08,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:09:47.843283+00:00
40,85398,STACO,2018-11-09,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:09:50.169754+00:00
41,85500,STACO,2018-11-12,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:09:54.975549+00:00
42,85602,STACO,2018-11-13,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:09:57.558923+00:00
43,85704,STACO,2018-11-14,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:09:59.910116+00:00
44,85806,STACO,2018-11-15,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:10:02.252366+00:00
45,85908,STACO,2018-11-16,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:10:04.527169+00:00
46,86010,STACO,2018-11-19,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:10:09.122468+00:00
47,86112,STACO,2018-11-21,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:10:12.622729+00:00
48,86214,STACO,2018-11-22,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:10:14.989948+00:00
49,86316,STACO,2018-11-23,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:10:17.221139+00:00
50,86418,STACO,2018-11-26,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:10:22.142454+00:00
51,86520,STACO,2018-11-27,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:10:24.421595+00:00
52,86622,STACO,2018-11-28,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:10:26.708398+00:00
53,86724,STACO,2018-11-29,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:10:29.255332+00:00
54,86826,STACO,2018-11-30,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:10:32.706086+00:00
55,86928,STACO,2018-12-03,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:10:37.185914+00:00
56,87030,STACO,2018-12-04,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:10:39.607482+00:00
57,87132,STACO,2018-12-05,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:10:42.037497+00:00
58,87234,STACO,2018-12-06,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:10:44.312069+00:00
59,87336,STACO,2018-12-07,0.48,NaN,NaN,0.48,0.0,2026-04-08T03:10:46.663078+00:00

STACO data is also not useful.